
services:
  mysql:
    container_name: ps-mysql
    image: jpb418/ccdc:prestashop-db
    restart: unless-stopped
    networks:
      - prestashop_network_testing
    # volumes:                            # Uncomment to have persistence to save the data across machies you have to build the images and push them to there respective repo (Same thing for presta shop)
    #   - ../database/db_data:/var/lib/mysql

  prestashop:
    container_name: prestashop
    image: jpb418/ccdc:prestashop
    restart: unless-stopped
    depends_on:
      - mysql
    ports:
      - 8080:80 
    networks:
      - prestashop_network_testing
    volumes:
      - ../prestashop/psdata:/var/www/html

networks:
  prestashop_network_testing:
    driver: bridge
